language: node_js
node_js:
- node
sudo: false
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: 2ZGFHmKZgbgF+IJ2HPCFTbvEYZZIraSClowJOgmAqXeROwEPAR6n58AN0PliX9YQGjgxEsrkm3gtwvfj9y+FQp54k8NzlzDv7YJQP8V/gMMT8fcFaIb4X02hBvY/SE/q6P9vbAQzEVimspfi/uRLlsAPmjUnBEOYcQDmG3tESxRqXzmN1heFMFj1M+TKVBK9FuTohE9UnSbzUWB5hLKULh87VIydisb9NRBhk84C0sX8p1FrHYCAf7QJOrDSSqUmbWG/cS/WepsWQLgWKpbXIvcU0OkA2A6qRS/Lny/DhIbBV79niuAQXkrVm3fpmSyTrzKJWEEqmCN9qTdND3gqdHVRYd2t3FxEVssqz+IgpQYjTbGJ/Yp6pVirAZMYqnQGW0WEH90fPToswcvwNNLGE58UBsUel7na387FzB/SqPNU2q4aqn7Y6LRcYbVJ6ZBpKA5NKlExebtseoFN1je0XmsbHZP6UPq6czvu26cTlDLTOr5+aIlAiSK+0JThlikW1y34bajNV0z/46sazlG4d18QQI5v5R69DMw+pyr8btKtTvZ50WHxM2sfVixzPXjYZlPIbETGKyxduAFwyAO1+nD01wQD1I6ItnL5KG4bZCwv3MC/QX+DRf0DPIq1mlXyumh6iuEzVKDl/FNGGB4Dv92LyJB1+x+RWeaPkfaUFkw=
  app: pipeline-devops-francisco1code
  edge: true
